version: '3.4'

services:
  trabalhosistemasweb2021:
    image: trabalhosistemasweb2021
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 5002:5000
    depends_on:
      - adminer

  # db:
  #   image: postgres:13
  #   container_name: popcornclub-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: T5sbHDJPfGk2QBqRlD02UBbC6Vb23JR9ePoJvX5SuxCKFOildxyTDIHJ56hIRyHX
  #   restart: always
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"


  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: ec2-23-23-199-57.compute-1.amazonaws.com
    ports:
      - "8080:8080"

# volumes:
#   pg_data:
